apiVersion: apps/v1
kind: Deployment                    
metadata:
  name: {{ .Values.postgres.name }} 
  labels:                          
    app: {{ .Values.postgres.name }} 
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:                  
      app: {{ .Values.postgres.name }}
      tier: postgres
  template:                         
    metadata:
      labels:                      
        app: {{ .Values.postgres.name }}
        tier: postgres
    spec:                           
      containers:
      - image: {{ .Values.postgres.container.image }}         
        name: {{ .Values.postgres.name }}
        env:       
        - name: POSTGRES_USER
          valueFrom:               
            secretKeyRef:
              name: book-shop-postgres-secret
              key: user
        - name: POSTGRES_PASSWORD
          valueFrom:               
            secretKeyRef:
              name: book-shop-postgres-secret
              key: password
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: book-shop-postgres-secret
              key: database
        ports:
        - containerPort: {{ .Values.postgres.container.port }}     
          name: postgres-port
        volumeMounts:
        - name: {{ .Values.postgres.name }}-pv
          mountPath: {{ .Values.postgres.volume.mountPath }} 
      volumes:                      
      - name: {{ .Values.postgres.name }}-pv
        persistentVolumeClaim:
          claimName: {{ .Values.postgres.name }}-pvc