apiVersion: v1
kind: PersistentVolume        
metadata:                          
  name: {{ .Values.postgres.name }}-pv
  labels:
    type: local
  namespace: {{ .Values.namespace }}
spec:   
  storageClassName: {{ .Values.postgres.volume.storageClassName }}         
  capacity:
    storage: {{ .Values.postgres.volume.pv.storage }}
  accessModes:
    - {{ .Values.postgres.volume.accessMode }}  
  hostPath:                      
    path: {{ .Values.postgres.volume.pv.hostPath }}   
  persistentVolumeReclaimPolicy: {{ .Values.postgres.volume.pv.persistentVolumeReclaimPolicy }}   
