apiVersion: v1                   
kind: Service                    
metadata:
  name: {{ .Values.postgres.name }}
  labels: 
    app: {{ .Values.postgres.name }}
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.postgres.service.type }}
  selector:             
    app: {{ .Values.postgres.name }}
    tier: postgres
  ports:
    - port: {{ .Values.postgres.service.port }}       
      targetPort: {{ .Values.postgres.container.port }} 