apiVersion: v1
kind: PersistentVolumeClaim        
metadata:                          
  name: {{ .Values.postgres.name }}-pvc
  labels:
    app: {{ .Values.postgres.name }}
  namespace: {{ .Values.namespace }}
spec:                              
  storageClassName: {{ .Values.postgres.volume.storageClassName }}      
  accessModes:
    - {{ .Values.postgres.volume.accessMode }}              
  resources:
    requests:
      storage: {{ .Values.postgres.volume.pvc.storage }}
