apiVersion: apps/v1           
kind: Deployment              
metadata:
  name: book-shop-backend    
  labels:                     
    app: book-shop-backend
spec:
  replicas: 1                 
  selector:
    matchLabels:              
      app: book-shop-backend
  template:                   
    metadata:
      labels:                 
        app: book-shop-backend
    spec:                     
      containers:
      - name: book-shop-backend
        image: registry.gitlab.com/shathacodes/observability-helm-charts/bookshopback
        imagePullPolicy: IfNotPresent
        ports:
          - name: http
            containerPort: 8080 
        resources:
          limits:
            cpu: 0.2
            memory: "300Mi"
        env:                  
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: postgres-user
              key: user
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-user-pass
              key: password
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            secretKeyRef:
              name: postgres-db-url
              key: url
        - name: SPRING_ZIPKIN_BASE_URL
          value: "http://tempo.monitoring:9411"
      imagePullSecrets:
      - name: gitlab-auth
---
apiVersion: v1                
kind: Service                 
metadata:                     
  name: book-shop-backend    
  labels:                     
    app: book-shop-backend
spec:                         
  type: NodePort 		
  selector:
    app: book-shop-backend   
  ports:                      
  - port: 8080
    protocol: TCP
    targetPort: 8080
    

