apiVersion: v1
kind: PersistentVolume            
metadata:
  name: postgres-pv
  labels:
    type: local
spec:
  storageClassName: standard       
  capacity:
    storage: 250Mi
  accessModes:
    - ReadWriteOnce
  hostPath:                      
    path: "/mnt/data"
  persistentVolumeReclaimPolicy: Retain  
---    
apiVersion: v1
kind: PersistentVolumeClaim        
metadata:                          
  name: postgres-pv-claim
  labels:
    app: book-shop
spec:                              
  storageClassName: standard      
  accessModes:
    - ReadWriteOnce              
  resources:
    requests:
      storage: 250Mi
---
apiVersion: v1                   
kind: Service                    
metadata:
  name: book-shop-postgres          
  labels:                        
    app: book-shop
spec:
  ports:
    - port: 5432 
  selector:                       
    app: book-shop
    tier: postgres
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment                    
metadata:
  name: book-shop-postgres             
  labels:                          
    app: book-shop
spec:
  selector:
    matchLabels:                  
      app: book-shop
      tier: postgres
  strategy:
    type: Recreate
  template:                         
    metadata:
      labels:                      
        app: book-shop
        tier: postgres
    spec:                           
      containers:
      - image: postgres:12.10          
        name: postgres
        env:       
        - name: POSTGRES_USER
          valueFrom:               
            secretKeyRef:
              name: postgres-user
              key: user
        - name: POSTGRES_PASSWORD
          valueFrom:               
            secretKeyRef:
              name: postgres-user-pass
              key: password
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: postgres-db-url
              key: database
        ports:
        - containerPort: 5432        
          name: postgres
        volumeMounts:
        - name: postgres-persistent-storage  
          mountPath: /var/lib/postgres
      volumes:                      
      - name: postgres-persistent-storage
        persistentVolumeClaim:
          claimName: postgres-pv-claim