apiVersion: v1                
kind: Service                 
metadata:                     
  name: {{ .Values.name }}-frontend 
  labels:                     
    app: {{ .Values.name }}-frontend 
  namespace: {{ .Values.namespace }}
spec:                         
  type: {{ .Values.frontend.service.type }}  	
  selector:
    app: {{ .Values.name }}-frontend  
  ports:                      
  - port: {{ .Values.frontend.service.port }}  	
    protocol: TCP
    targetPort: {{ .Values.frontend.container.port }}  	