apiVersion: apps/v1            
kind: Deployment                
metadata:
  name: {{ .Values.name }}-frontend      
  labels:                     
    app: {{ .Values.name }}-frontend 
  namespace: {{ .Values.namespace }} 
spec:
  replicas:  {{ .Values.replicaCount }}                    
  selector:                     
    matchLabels:                
      app: {{ .Values.name }}-frontend 
  template:                     
    metadata:
      labels:                   
        app: {{ .Values.name }}-frontend 
    spec:                       
      containers:
      - name: {{ .Values.name }}-frontend 
        image: {{ .Values.frontend.container.image }}:{{ .Values.frontend.container.tag }}
        imagePullPolicy: {{ .Values.imagePullPolicy }} 
        ports:
          - name:  frontend-port
            containerPort: {{ .Values.frontend.container.port }} 
        resources:
          limits:
            cpu: {{ .Values.frontend.resources.cpu }}
            memory: {{ .Values.frontend.resources.memory }} 
        env:
        - name: SPRING_ZIPKIN_BASE_URL
          value: {{ .Values.frontend.env.zipkin }}
