apiVersion: v1                
kind: Service                 
metadata:                     
  name: {{ .Values.name }}-back
  labels:                     
    app: {{ .Values.name }}-back 
  namespace: {{ .Values.namespace }}
spec:                         
  type: {{ .Values.back.service.type }}  	
  selector:
    app: {{ .Values.name }}-back  
  ports:                      
  - port: {{ .Values.back.service.port }}  	
    protocol: TCP
    targetPort: {{ .Values.back.container.port }}  	
    

