apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-ingress  # explicit deny on all pods in namespace
  namespace: {{ .Values.namespace }}
spec:
  podSelector: {}
  policyTypes:
  - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: my-network-policy
  namespace: {{ .Values.namespace }}
spec:
  namespaceSelector:
    matchLabels: # matchExpression
      kubernetes.io/metadata.name: {{ .Values.namespace }}
  podSelector:
    matchLabels:
      app: {{ .Values.name }}-back
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: {{ .Values.name }}-front  
      ports:
        - protocol: TCP
          port: {{ .Values.back.container.port }}
