apiVersion: v1                
kind: Service                 
metadata:                     
  name: {{ .Values.name }}-backend
  labels:                     
    app: {{ .Values.name }}-backend 
  namespace: {{ .Values.namespace }}
spec:                         
  type: {{ .Values.backend.service.type }}  	
  selector:
    app: {{ .Values.name }}-backend  
  ports:                      
  - port: {{ .Values.backend.service.port }}  	
    protocol: TCP
    targetPort: {{ .Values.backend.container.port }}  	
    

