apiVersion: apps/v1           
kind: Deployment              
metadata:
  name: {{ .Values.name }}-backend      
  labels:                     
    app: {{ .Values.name }}-backend  
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}                 
  selector:
    matchLabels:              
      app: {{ .Values.name }}-backend  
  template:                   
    metadata:
      labels:                 
        app: {{ .Values.name }}-backend  
    spec:                     
      containers:
      - name: {{ .Values.name }}-backend  
        image: {{ .Values.backend.container.image }}:{{ .Values.backend.container.tag }}
        imagePullPolicy: {{ .Values.imagePullPolicy }} 
        ports:
          - name:  backend-port
            containerPort: {{ .Values.backend.container.port }}   
        resources:
          limits:
            cpu: {{ .Values.backend.resources.cpu }}
            memory: {{ .Values.backend.resources.memory }} 
        env:                  
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: book-shop-postgres-secret
              key: user
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: book-shop-postgres-secret
              key: password
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            secretKeyRef:
              name: book-shop-postgres-secret
              key: url
        - name: SPRING_ZIPKIN_BASE_URL
          value: {{ .Values.backend.env.zipkin }} 