replicaCount: 1
version : v2

name: book-shop
imagePullPolicy: IfNotPresent
namespace: webapp
deploymentLabels:
  tier: presentation

monitoring:
  namespace: monitoring

back:
  container:
    image: shatha20/bookshopback
    tag: devops
    port: 8080
  service:
    type: ClusterIP
    port: 8080
    serviceMonitor:
      serviceMonitorSelector: prometheus
      interval: 30s
      path: /actuator/prometheus
  env:
    zipkin:  "http://tempo.monitoring:9411"

front:
  container:
    image: shatha20/bookshopfront
    tag: devops
    port: 9000
  service:
    type: LoadBalancer
    port: 9005
    serviceMonitor:
      serviceMonitorSelector: prometheus
      interval: 30s
      path: /actuator/prometheus
  env:
    zipkin:  "http://tempo.monitoring:9411"
