version: '3.4'

services:
#  backend:
#    image: "shatha20/bookshopback:0.0.1"
#    environment:
#      - "spring.datasource.url=jdbc:postgresql://db:5432/${POSTGRES_DB}"
#      - "spring.datasource.password=${POSTGRES_PASSWORD}"
#      - "spring.datasource.username=${POSTGRES_USER}"
#    ports:
#      - 8080:8080
#    networks:
#      - app-network
#    depends_on:
#      - db
#
#  frontend:
#    image: "shatha20/bookshopfront:0.0.1"
#    ports:
#      - 9001:9000
#    environment:
#      - "backend.prefix.url=http://backend:8080"
#    networks:
#      - app-network
#    depends_on:
#      - backend

  db:
    image: postgres:12.10
    restart: on-failure
    ports:
      - 5432:5432 
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"
    networks:
      - app-network
      
networks:
  app-network:
