apiVersion: apps/v1            
kind: Deployment                
metadata:
  name: {{ .Values.name }}-front      
  labels:                     
    app: {{ .Values.name }}-front 
  namespace: {{ .Values.namespace }} 
spec:
  replicas:  {{ .Values.replicaCount }}                    
  selector:                     
    matchLabels:                
      app: {{ .Values.name }}-front 
  template:                     
    metadata:
      labels:                   
        app: {{ .Values.name }}-front 
    spec:                       
      containers:
      - name: {{ .Values.name }}-front 
        image: {{ .Values.front.container.image }}:{{ .Values.front.container.tag }}
        imagePullPolicy: {{ .Values.imagePullPolicy }} 
        ports:
          - name:  front-port
            containerPort: {{ .Values.front.container.port }} 
        resources:
          limits:
            cpu: {{ .Values.front.resources.cpu }}
            memory: {{ .Values.front.resources.memory }} 
        env:
        - name: SPRING_ZIPKIN_BASE_URL
          value: {{ .Values.front.env.zipkin }}
        - name: BACK_PREFIX_URL
          value: {{ .Values.front.env.back }}
