#apiVersion: apps/v1            
#kind: Deployment                
#metadata:
#  name: {{ .Values.name }}-front-{{ .Values.version }}    
#  labels:                     
#    app: {{ .Values.name }}-front-{{ .Values.version }}
#    version: {{ .Values.version }}
#    {{- range $key, $val := .Values.deploymentLabels }}
#    {{ $key }}: {{ $val | quote }}
#    {{- end}}
#  namespace: {{ .Values.namespace }} 
#spec:
#  replicas:  {{ .Values.replicaCount }}                    
#  selector:                     
#    matchLabels:                
#      app: {{ .Values.name }}-front-{{ .Values.version }}
#      version: {{ .Values.version }}
#  template:                     
#    metadata:
#      labels:                   
#        app: {{ .Values.name }}-front-{{ .Values.version }}
#        version: {{ .Values.version }}
#    spec:                       
#      containers:
#      - name: {{ .Values.name }}-front 
#        image: {{ .Values.front.container.image }}:{{ .Values.front.container.tag }}
#        imagePullPolicy: {{ .Values.imagePullPolicy }} 
#        ports:
#          - name:  front-port
#            containerPort: {{ .Values.front.container.port }} 
#        env:
#        - name: SPRING_ZIPKIN_BASE_URL
#          value: {{ .Values.front.env.zipkin }}
#        - name: BACKEND_PREFIX_URL
#          value: http://{{ .Values.name }}-back-{{ .Values.version }}:{{ .Values.back.service.port }}
#