apiVersion: v1                
kind: Service                 
metadata:                     
  name: {{ .Values.name }}-front-{{ .Values.version }}
  annotations:
    service.beta.kubernetes.io/azure-dns-label-name: bookshop
  labels:                     
    app: {{ .Values.name }}-front-{{ .Values.version }}
    version: {{ .Values.version }} 
  namespace: {{ .Values.namespace }}
spec:                         
  type: {{ .Values.front.service.type }}  	
  selector:
    app: {{ .Values.name }}-front-{{ .Values.version }}
    version: {{ .Values.version }}  
  ports:                      
  - port: {{ .Values.front.service.port }}  	
    protocol: TCP
    targetPort: {{ .Values.front.container.port }}  	