{
 "title": "Logs",
 "description": "Dashboard for K8s logs.",
 "tags": [
  "logs",
  "loki"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "node",
    "query": {
     "query": "label_values(kube_node_info,node)"
    }
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(kube_namespace_labels,namespace)"
    }
   },
   {
    "name": "container",
    "label": "container",
    "query": {
     "query": "label_values(kube_pod_container_info{namespace=~\"$namespace\"},container)"
    }
   },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values(kube_pod_container_info{namespace=~\"$namespace\",container=~\"$container\"},pod)"
    }
   },
   { "name": "search", "label": "search" }
  ]
 },
 "panels": [
  {
   "title": "Centralized logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "{container=~\"$container\", namespace=\"$namespace\", pod=~\"$pod\"} |~ \"(?i)$search\""
    }
   ]
  },
  {
   "title": "Logs per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "count_over_time({container=~\"$container\", namespace=\"$namespace\", pod=~\"$pod\"}[1m])",
     "legendFormat": "{{ app }}"
    }
   ]
  },
  {
   "title": "Error logs per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "count_over_time({container=~\"$container\", namespace=\"$namespace\", pod=~\"$pod\"} |~ \"(?i)error\"[1m])",
     "legendFormat": "{{ app }}"
    }
   ]
  }
 ]
}